[theme]
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f3f5f9"
textColor = "#0b0b0b"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
